name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy

      - name: Wait for Redis
        run: |
          for i in {1..10}; do
            if nc -z localhost 6379; then
                echo "Redis is ready";
                exit 0;
              fi;
              echo "Waiting for Redis to start...";
              sleep 3;
            done;
            echo "Redis did not start in time";
            exit 1

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./tests/...
